<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_cypress-realworld-app</name>
   <tag></tag>
   <elementGuidId>7cd4dad0-9ea0-4d4e-8890-71d73a478d36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='repository-container-header']/div/div/div/strong/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong.mr-2.flex-self-stretch > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;cypress-realworld-app&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9162b213-5f67-4d54-bbe5-2804244a6bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pjax</name>
      <type>Main</type>
      <value>#repo-content-pjax-container</value>
      <webElementGuid>3f542a29-21a4-4df8-a664-e5fd3ac6b8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-turbo-frame</name>
      <type>Main</type>
      <value>repo-content-turbo-frame</value>
      <webElementGuid>8d53a4bb-78b5-4747-8d70-04943afe8d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cypress-io/cypress-realworld-app</value>
      <webElementGuid>667120b7-4cca-441a-b4ba-4eb0757d4155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cypress-realworld-app</value>
      <webElementGuid>a33e33a5-7a00-4b5f-b491-4913a109ba98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repository-container-header&quot;)/div[@class=&quot;d-flex flex-nowrap flex-justify-end mb-3  px-3 px-lg-5&quot;]/div[@class=&quot;flex-auto min-width-0 width-fit&quot;]/div[@class=&quot;d-flex flex-wrap flex-items-center wb-break-word f3 text-normal&quot;]/strong[@class=&quot;mr-2 flex-self-stretch&quot;]/a[1]</value>
      <webElementGuid>d26e66f9-cf32-4078-8614-cd138b81d9fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repository-container-header']/div/div/div/strong/a</value>
      <webElementGuid>66a39715-807c-4e79-8fca-77d7072cbc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'cypress-realworld-app')]</value>
      <webElementGuid>bb71f229-da47-4ea9-91a9-420365a29557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/following::a[1]</value>
      <webElementGuid>04e2e811-8637-4139-9e57-1858627aae08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cypress-io'])[1]/following::a[1]</value>
      <webElementGuid>792c6580-c44d-4cc0-b1bb-15b44a45dda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[1]/preceding::a[1]</value>
      <webElementGuid>409359c2-975e-4bdc-a097-ec277b5c2d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='cypress-realworld-app']/parent::*</value>
      <webElementGuid>ad173b3e-2236-437f-a8d8-ca176698b838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cypress-io/cypress-realworld-app')]</value>
      <webElementGuid>4ee7a785-ebf3-40dc-9404-29062de11e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong/a</value>
      <webElementGuid>2a60fe1e-c84f-4bb0-856d-53f1628addbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cypress-io/cypress-realworld-app' and (text() = 'cypress-realworld-app' or . = 'cypress-realworld-app')]</value>
      <webElementGuid>92791168-ee35-4612-95be-a045bf28ac05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
