<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Elements_banner-image</name>
   <tag></tag>
   <elementGuidId>72d188e7-db58-401d-bce5-3fc12cb73da3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.banner-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Selenium Online Training&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a739a29-0569-4967-88f0-99e973f73196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner-image</value>
      <webElementGuid>f387d78d-6826-4e78-be2f-7226831fa08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/WB.svg</value>
      <webElementGuid>9bcb4c90-9296-40af-ba27-93c0a3178430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Selenium Online Training</value>
      <webElementGuid>82399ec8-a842-47ac-a7bd-3ad4ddf1c650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-height&quot;]/div[@class=&quot;home-content&quot;]/div[@class=&quot;home-banner&quot;]/a[1]/img[@class=&quot;banner-image&quot;]</value>
      <webElementGuid>9199ee2d-53a4-4a5e-b57d-ec5ffc278830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/a/img</value>
      <webElementGuid>e90eab9f-1820-4837-b3ba-4405057ccd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Selenium Online Training']</value>
      <webElementGuid>104fa427-dd8e-4982-abfd-82c615c34168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/img</value>
      <webElementGuid>e2ed6e5b-6500-4e83-9a6d-7c9279686634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/WB.svg' and @alt = 'Selenium Online Training']</value>
      <webElementGuid>c9b60e51-a4f0-4d24-a127-faa1f38f4099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
