<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Section of Buttons</name>
   <tag></tag>
   <elementGuidId>9dbd7dee-2bad-4da5-8fc5-baa37056216f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Section_of_Buttons']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Section_of_Buttons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Section_of_Buttons</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef1200a0-b79f-4542-bcee-b121df5ac7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Section_of_Buttons</value>
      <webElementGuid>67fc6f81-6936-4191-b7a8-14b29b111271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Section of Buttons</value>
      <webElementGuid>c77f8d22-2c83-40af-bc1f-e97d8383c4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Section_of_Buttons&quot;)</value>
      <webElementGuid>a92aa518-a78c-4178-beca-a13aa3935269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='Section_of_Buttons']</value>
      <webElementGuid>15f142b9-1747-4e48-8d97-21d6cfb0d6f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-579']/div/div/div/div/div[2]/div/div[2]/div/h1/span</value>
      <webElementGuid>911cbdf0-36c6-4224-909d-c026999f17d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Properly structuring your page objects'])[1]/following::span[1]</value>
      <webElementGuid>4183d18f-a3f6-46db-838c-713542609238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to deal with a large page that has many elements and divisions?'])[1]/following::span[1]</value>
      <webElementGuid>2391457f-a186-4623-b525-df8c9cb08cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Button'])[1]/preceding::span[1]</value>
      <webElementGuid>7b35fe48-1fa9-4d7d-a0b9-d04c9199a86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Button'])[2]/preceding::span[1]</value>
      <webElementGuid>d06b2741-c177-4c73-84a7-865092b4d1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Section of Buttons']/parent::*</value>
      <webElementGuid>7393e2e0-e6d8-447d-97ac-9becaf82353b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>5a77fa6f-dc77-4fd2-8bf0-cb55d6d4627d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'Section_of_Buttons' and (text() = 'Section of Buttons' or . = 'Section of Buttons')]</value>
      <webElementGuid>ddf65c01-9928-4d60-b0ca-dbb67b0cc85d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
